export * from './ping.controller';
export * from './filmes.controller';
export * from './user.controller';
export * from './filmes-genero.controller';
export * from './genero-filmes.controller';
export * from './user-lista-filmes.controller';
export * from './lista-filmes-user.controller';
export * from './filmes-lista-filmes.controller';
export * from './lista-filmes-filmes.controller';
